name: 23H2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Show available disk space before build
        run: Get-PSDrive -PSProvider FileSystem

      - name: Build
        run: pwsh uup-dump-get-windows-iso.ps1 23H2 c:/output

      - name: Show available disk space after build
        run: Get-PSDrive -PSProvider FileSystem

      - name: Build summary
        run: |
          $iso = Get-Content (Resolve-Path c:/output/*.json) | ConvertFrom-Json
          Add-Content $env:GITHUB_STEP_SUMMARY @"
          | Property | Value |
          | :--- | :--- |
          | Name | $($iso.name) |
          | Build | $($iso.build) |
          | Checksum | $($iso.checksum) |
          | Image Name | $($iso.images[0].name) |
          "@

      - name: Install rclone
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://downloads.rclone.org/rclone-current-windows-amd64.zip -OutFile rclone.zip
          Expand-Archive rclone.zip -DestinationPath .
          $env:PATH += ";$PWD\rclone-*-windows-amd64"

      - name: Configure rclone
        shell: pwsh
        run: |
          $configPath = "$env:USERPROFILE\.config\rclone\rclone.conf"
          New-Item -ItemType Directory -Path (Split-Path $configPath) -Force | Out-Null
          @"
          [gdrive]
          type = drive
          token = $env:GDRIVE_TOKEN
          "@ | Set-Content -Path $configPath

      - name: Upload to Google Drive
        shell: pwsh
        run: |
          .\rclone.exe copy c:/output gdrive:23H2 --drive-chunk-size 64M --progress
